# Generated by Django 5.2.10 on 2026-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("heading", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=15)),
                ("desc", models.CharField(max_length=500)),
                ("my_pic", models.CharField(max_length=500)),
                ("background", models.CharField(max_length=500)),
                ("resume", models.CharField(max_length=500)),
                ("is_available", models.BooleanField(default=False)),
            ],
        ),
    ]
