# Generated by Django 5.2.10 on 2026-02-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="name",
            new_name="fname",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="lname",
            field=models.CharField(default="", max_length=15),
        ),
    ]
