# Generated by Django 5.2.10 on 2026-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_name_sitesettings_fname_sitesettings_lname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="background",
            field=models.ImageField(upload_to="home/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="my_pic",
            field=models.ImageField(upload_to="home/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="resume",
            field=models.FileField(upload_to="home/"),
        ),
    ]
