# Generated by Django 5.2.10 on 2026-02-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("desc", models.CharField(max_length=500)),
                ("blog_text", models.CharField(max_length=2000)),
                ("git_link", models.CharField(max_length=500)),
                ("media", models.CharField(max_length=500)),
                ("blog_link", models.CharField(max_length=500)),
            ],
        ),
    ]
