# Generated by Django 5.2.10 on 2026-02-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="git_link",
        ),
    ]
