# Generated by Django 5.2.10 on 2026-02-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_blog_git_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="blog_link",
        ),
    ]
