# Generated by Django 5.2.10 on 2026-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_blog_blog_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="media",
            field=models.ImageField(upload_to="blogs/"),
        ),
    ]
