# Generated by Django 5.2.10 on 2026-02-10 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=500)),
                ("desc", models.CharField(max_length=2000)),
                ("date", models.DateField(default=datetime.date.today)),
                ("link", models.CharField(max_length=500)),
            ],
        ),
    ]
