# Generated by Django 5.2.10 on 2026-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievements",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
