# Generated by Django 5.2.10 on 2026-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_achievements_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="image",
            field=models.ImageField(upload_to="achievements/"),
        ),
    ]
