# Generated by Django 5.2.10 on 2026-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("text", models.CharField(max_length=30)),
                ("media", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=50)),
            ],
        ),
    ]
