# Generated by Django 5.2.10 on 2026-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialcard",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
