# Generated by Django 5.2.10 on 2026-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0002_socialcard_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialcard",
            name="media",
            field=models.CharField(max_length=500),
        ),
    ]
