# Generated by Django 5.2.10 on 2026-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0003_alter_socialcard_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialcard",
            name="media",
            field=models.ImageField(upload_to="socials/"),
        ),
    ]
