# Generated by Django 5.2.10 on 2026-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("desc", models.CharField(max_length=500)),
                ("git_link", models.CharField(max_length=500)),
                ("media", models.CharField(max_length=500)),
                ("live_link", models.CharField(max_length=500)),
                ("is_available", models.BooleanField(default=False)),
            ],
        ),
    ]
