# Generated by Django 5.2.10 on 2026-02-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcard",
            old_name="name",
            new_name="title",
        ),
    ]
