# Generated by Django 5.2.10 on 2026-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_name_projectcard_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcard",
            name="media",
            field=models.ImageField(upload_to="projects/"),
        ),
    ]
